Jr/dev calculate bingo
EnigmaBay/lingobingojs pull request #23
Opened 2022-10-10 18:19 UTC by nojronatron

Designed and implemented bingo checking functions with Jest test cases and data for testing. Refactored several times to integrate into the Gameboard. BINGO result rendering is totally temporary and can be changed i.e. Gameboard still shows board while a Bingo is announced with future Bingo-party effects etc.

- [X] Develop components that can be called to test for Bingo.
- [X] Develop Jest test cases for each bingo checking component.
- [X] Integrate bingo checking into GameBoard.
- [X] Set placeholder logic to indicate Bingo when it happens.
- [X] All tests are passing.

2022-10-11 01:42 UTC, schaferyan reviewed
Looks good and it works! My only question is about the test files. I may be missing something but it looks like you could just parse the json file into a js object, then access each pattern array directly rather than manually copying each pattern to a new variable one tile at a time.

2022-10-11 01:46 UTC, nojronatron commented
That's a good idea! I'll update this PR with that update.

2022-10-11 03:42 UTC, nojronatron commented
I refactored the test files to use object literals. Let me know if this was/not what you were talking about. Fill me in if not. In any case it was a good exercise. :smiley:

2022-10-12 23:25 UTC, schaferyan commented
This is a little bit different from what I imagined, but it's definitely condensed and easier to read. If you wanted to take it a step further, I think you can safely pass instance.dauberedTiles directly instead of copying into to a new tileList with `foreach()` and `push()`. I'll see if I can recommend this as a change.

2022-10-12 23:45 UTC, schaferyan commented on src/testLib/calcBingoV.test.js
> +  const tileList = [];
```suggestion

```

2022-10-12 23:46 UTC, schaferyan commented on src/testLib/calcBingoV.test.js
> +  instance.dauberedTiles.forEach(tile => tileList.push(tile));
```suggestion

```

2022-10-12 23:47 UTC, schaferyan commented on src/testLib/calcBingoV.test.js
> +      dauberedTiles: tileList
```suggestion
      dauberedTiles: instance.dauberedTiles
```

2022-10-12 23:50 UTC, schaferyan requested changes
If I did this correctly, you should see a suggested change in the calcBingoV.test.js that demonstrates my meaning

2022-10-13 19:55 UTC, nojronatron commented
Updated code per Ryan's suggestions. Tests running and passing.

2022-10-14 18:22 UTC, schaferyan approved these changes
Looks good!

2022-10-14 18:23 UTC, merged